version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests=true -B -pl janusgraph-$MODULE -am -Dmaven.compiler.showWarnings=false -Dmaven.javadoc.skip=true
      - mvn verify -pl janusgraph-$MODULE $ARGS
  post_build:
    commands:
      - echo Build completed on `date`
      - ln -s ./janusgraph-$MODULE ./module 
artifacts:
  base-directory: module
  files:
    - target/**/*
